"use client";
import {useEffect,useRef,useState} from "react";
import {Engine,Scene,Vector3,Color3,Color4,MeshBuilder,StandardMaterial,HemisphericLight,DirectionalLight,ArcRotateCamera,TransformNode,ShadowGenerator,KeyboardEventTypes,Animation,DynamicTexture} from "@babylonjs/core";

type Move={x:number;y:number};
const DEMO_MODE=process.env.NEXT_PUBLIC_DEMO_MODE!=="false";
export default function GameClient(){const canvas=useRef<HTMLCanvasElement>(null);const move=useRef<Move>({x:0,y:0});const jump=useRef(false);const [msg,setMsg]=useState("استكشف الجزيرة");const [shop,setShop]=useState(false);const [user,setUser]=useState("زائر");const playerPos=useRef({x:0,y:1,z:0});
useEffect(()=>{const c=canvas.current;if(!c)return;const engine=new Engine(c,true,{preserveDrawingBuffer:false,stencil:false,antialias:true,adaptToDeviceRatio:false});const scene=new Scene(engine);scene.clearColor=new Color4(.42,.78,.9,1);scene.collisionsEnabled=true;const camera=new ArcRotateCamera("cam",Math.PI/2,1.05,11,new Vector3(0,2,0),scene);camera.lowerRadiusLimit=7;camera.upperRadiusLimit=14;camera.attachControl(c,true);camera.inputs.removeByType("ArcRotateCameraPointersInput");new HemisphericLight("sky",new Vector3(0,1,0),scene).intensity=.85;const sun=new DirectionalLight("sun",new Vector3(-.5,-1,.4),scene);sun.position=new Vector3(18,28,-14);sun.intensity=1.1;const shadow=new ShadowGenerator(512,sun);shadow.useBlurExponentialShadowMap=true;shadow.blurKernel=16;
const mat=(name:string,color:Color3)=>{const m=new StandardMaterial(name,scene);m.diffuseColor=color;m.specularColor=Color3.Black();return m};const sand=mat("sand",new Color3(.84,.72,.42));const grass=mat("grass",new Color3(.16,.55,.3));const water=mat("water",new Color3(.05,.45,.66));water.alpha=.82;const trunk=mat("trunk",new Color3(.3,.16,.07));const leaf=mat("leaf",new Color3(.08,.45,.24));
const ocean=MeshBuilder.CreateGround("ocean",{width:220,height:220},scene);ocean.material=water;ocean.position.y=-.65;const island=MeshBuilder.CreateCylinder("island",{height:1.2,diameter:42,tessellation:48},scene);island.material=sand;island.position.y=-.1;island.checkCollisions=true;const top=MeshBuilder.CreateCylinder("top",{height:.65,diameterTop:34,diameterBottom:38,tessellation:48},scene);top.material=grass;top.position.y=.55;top.checkCollisions=true;
for(let i=0;i<28;i++){const a=(i/28)*Math.PI*2+(i%3)*.14,r=11+(i%5)*1.15;const t=MeshBuilder.CreateCylinder(`t${i}`,{height:2.8,diameterTop:.38,diameterBottom:.58,tessellation:8},scene);t.material=trunk;t.position=new Vector3(Math.cos(a)*r,2,Math.sin(a)*r);t.rotation.z=(i%2?.08:-.08);const crown=MeshBuilder.CreateSphere(`l${i}`,{diameter:2.7,segments:8},scene);crown.scaling.y=.62;crown.position=t.position.add(new Vector3(0,1.7,0));crown.material=leaf;shadow.addShadowCaster(t);shadow.addShadowCaster(crown)}
const avatar=new TransformNode("avatar",scene);const body=MeshBuilder.CreateCapsule("body",{height:1.8,radius:.42,tessellation:12},scene);body.parent=avatar;body.position.y=1.15;body.material=mat("shirt",new Color3(.95,.46,.15));const head=MeshBuilder.CreateSphere("head",{diameter:.72,segments:12},scene);head.parent=avatar;head.position.y=2.2;head.material=mat("skin",new Color3(.65,.38,.2));const hat=MeshBuilder.CreateCylinder("hat",{height:.2,diameter:1.05,tessellation:16},scene);hat.parent=avatar;hat.position.y=2.62;hat.material=mat("hatmat",new Color3(.98,.82,.2));shadow.addShadowCaster(body);shadow.addShadowCaster(head);shadow.addShadowCaster(hat);avatar.position=new Vector3(0,1,0);camera.lockedTarget=body;
const keys=new Set<string>();scene.onKeyboardObservable.add(k=>{const key=k.event.key.toLowerCase();if(k.type===KeyboardEventTypes.KEYDOWN){keys.add(key);if(key===" ")jump.current=true}else keys.delete(key)});let vy=0,onGround=true;let saveTimer=0;scene.onBeforeRenderObservable.add(()=>{const dt=Math.min(engine.getDeltaTime()/1000,.033);let mx=move.current.x,my=move.current.y;if(keys.has("w")||keys.has("arrowup"))my=-1;if(keys.has("s")||keys.has("arrowdown"))my=1;if(keys.has("a")||keys.has("arrowleft"))mx=-1;if(keys.has("d")||keys.has("arrowright"))mx=1;const len=Math.hypot(mx,my);if(len>.05){mx/=Math.max(1,len);my/=Math.max(1,len);const forward=new Vector3(Math.sin(camera.alpha),0,Math.cos(camera.alpha));const right=new Vector3(forward.z,0,-forward.x);const dir=forward.scale(-my).add(right.scale(mx));avatar.position.addInPlace(dir.scale(4.2*dt));avatar.rotation.y=Math.atan2(dir.x,dir.z);body.scaling.y=1+Math.sin(performance.now()*.014)*.025}const radial=Math.hypot(avatar.position.x,avatar.position.z);if(radial>16.2){const s=16.2/radial;avatar.position.x*=s;avatar.position.z*=s}if(jump.current&&onGround){vy=5.3;onGround=false;jump.current=false}vy-=12*dt;avatar.position.y+=vy*dt;if(avatar.position.y<=1){avatar.position.y=1;vy=0;onGround=true}playerPos.current={x:avatar.position.x,y:avatar.position.y,z:avatar.position.z};saveTimer+=dt;if(saveTimer>12){saveTimer=0;if(!DEMO_MODE){fetch("/api/player",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(playerPos.current)}).catch(()=>{})}}});
const resize=()=>{const dpr=Math.min(window.devicePixelRatio||1,1.5);engine.setHardwareScalingLevel(1/dpr);engine.resize()};resize();window.addEventListener("resize",resize);engine.runRenderLoop(()=>scene.render());return()=>{window.removeEventListener("resize",resize);scene.dispose();engine.dispose()};},[]);
function setupJoystick(el:HTMLDivElement|null){if(!el)return;const stick=el.firstElementChild as HTMLElement;const reset=()=>{move.current={x:0,y:0};stick.style.transform="translate(0,0)"};const update=(e:PointerEvent)=>{const r=el.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),m=Math.min(35,Math.hypot(x,y)),a=Math.atan2(y,x),dx=Math.cos(a)*m,dy=Math.sin(a)*m;stick.style.transform=`translate(${dx}px,${dy}px)`;move.current={x:dx/35,y:dy/35}};el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);update(e)};el.onpointermove=e=>{if(el.hasPointerCapture(e.pointerId))update(e)};el.onpointerup=reset;el.onpointercancel=reset}
async function login(){if(DEMO_MODE){setUser("لاعب تجريبي");setMsg("تم الدخول في الوضع التجريبي");return}try{if(!window.Pi)throw new Error("افتح اللعبة من Pi Browser");window.Pi.init({version:"2.0",sandbox:process.env.NEXT_PUBLIC_PI_SANDBOX==="true"});const a=await window.Pi.authenticate(["username","payments"],async()=>{});const r=await fetch("/api/auth/pi",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accessToken:a.accessToken})});if(!r.ok)throw new Error("فشل تسجيل الدخول");const d=await r.json();setUser(d.player.pi_username);setMsg(`أهلًا ${d.player.pi_username}`)}catch(e){setMsg(e instanceof Error?e.message:"خطأ")}}
async function buy(code:"sun_hat"|"trail_pack"){if(DEMO_MODE){setMsg(`تم شراء ${code==="sun_hat"?"قبعة الشمس":"حقيبة الرحلة"} تجريبيًا`);setShop(false);return}try{if(!window.Pi)throw new Error("Pi SDK غير متاح");const r=await fetch("/api/shop/order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemCode:code})});if(!r.ok)throw new Error("سجّل الدخول أولًا");const o=await r.json();window.Pi.createPayment({amount:o.amount,memo:`Island Way: ${o.name}`,metadata:{orderId:o.orderId,itemCode:code}},{onReadyForServerApproval:async paymentId=>{const x=await fetch("/api/pi/payments/approve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId,orderId:o.orderId})});if(!x.ok)throw new Error("Approval failed")},onReadyForServerCompletion:async(paymentId,txid)=>{const x=await fetch("/api/pi/payments/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId,txid,orderId:o.orderId})});if(!x.ok)throw new Error("Completion failed");setMsg("تم الشراء بنجاح");setShop(false)},onCancel:()=>setMsg("تم إلغاء الدفع"),onError:e=>setMsg(e.message)})}catch(e){setMsg(e instanceof Error?e.message:"تعذر الشراء")}}
return <div className="game-shell"><canvas ref={canvas} className="game-canvas"/><div className="hud"><div className="topbar"><div className="panel"><div className="brand">ISLAND WAY {DEMO_MODE&&<small>DEMO</small>}</div><div className="stats"><span>👤 {user}</span><span>⭐ 1</span></div></div><div className="actions"><button className="btn" onClick={login}>Pi Login</button><button className="btn primary" onClick={()=>setShop(true)}>المتجر</button></div></div><div className="panel message">{msg}</div><div className="joystick" ref={setupJoystick}><div className="stick"/></div><button className="jump" onPointerDown={()=>jump.current=true}>قفز</button></div>{shop&&<div className="modal-backdrop"><div className="modal"><button className="btn close" onClick={()=>setShop(false)}>✕</button><h2>متجر الجزيرة</h2><div className="shop-grid"><div className="item"><b>قبعة الشمس</b><p>0.01 Pi</p><button className="btn primary" onClick={()=>buy("sun_hat")}>شراء</button></div><div className="item"><b>حقيبة الرحلة</b><p>0.02 Pi</p><button className="btn primary" onClick={()=>buy("trail_pack")}>شراء</button></div></div></div></div>}</div>}
